version: '3'

services:
  daemon_health_check:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "18091:18091"
      - "5000:5000"
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - MONEROD_RPC_URL=127.0.0.1
      - MONEROD_RPC_PORT=18081
      - MONEROD_RPC_USER=
      - MONEROD_RPC_PASSWORD=
      - OFFSET=12
      - OFFSET_UNIT=minutes
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
